### PR TITLE
cli: fix issue when sorting by run_number or human_readable size

### LINKED ISSUE #40: cli: `run_number` and human readable `size` not being properly sorted
Currently, since `run_number` and `size` (when the human readable flag is activated) are represented as strings, they aren't properly sorted. For example, by running the `list` command with these flags:

```
reana-client-go list --sort run_number
NAME                          RUN_NUMBER   CREATED               STARTED               ENDED                 STATUS  
root6-roofit                  9            2022-07-20T12:08:38   2022-07-20T12:09:03   2022-07-20T12:09:19   finished
root6-roofit                  8            2022-07-20T12:08:36   2022-07-20T12:08:58   2022-07-20T12:09:14   finished
root6-roofit                  7            2022-07-20T12:08:34   2022-07-20T12:08:53   2022-07-20T12:09:12   finished
root6-roofit                  6            2022-07-20T12:08:31   2022-07-20T12:08:47   2022-07-20T12:09:03   finished
root6-roofit                  5            2022-07-20T12:08:29   2022-07-20T12:08:42   2022-07-20T12:08:58   finished
root6-roofit                  4.2          2022-07-20T12:07:05   2022-07-20T12:07:19   2022-07-20T12:07:38   finished
root6-roofit                  4.1          2022-07-20T12:06:08   2022-07-20T12:06:21   2022-07-20T12:06:36   finished
root6-roofit                  4            2022-07-06T12:30:19   2022-07-06T12:30:34   2022-07-06T12:30:53   finished
root6-roofit                  3            2022-07-06T12:11:26   2022-07-06T12:11:40   2022-07-06T12:11:41   failed  
root6-roofit                  2.1          2022-07-06T12:10:39   -                     -                     deleted 
my-atlas-recast-analysis      2            2022-07-20T12:03:21   2022-07-20T12:03:34   2022-07-20T12:06:49   finished
root6-roofit                  2            2022-07-06T12:09:03   2022-07-06T12:09:18   2022-07-06T12:10:04   finished
root6-roofit                  10           2022-07-20T12:08:40   2022-07-20T12:09:09   2022-07-20T12:09:24   finished
workflow                      1            2022-07-20T12:08:06   2022-07-20T12:08:37   2022-07-20T12:08:56   finished
```
As you can see, the row with the run number 10 should be the first one, but they're being sorted as a string. The human readable size has a similar problem.
These columns shouldn't simply be sorted based on their value types. Note that the run_number has to take dots into consideration (e.g. 1.10 should be greater than 1.2) and that the human readable size comes in the format `X KiB`.

Also read https://github.com/reanahub/reana-client/issues/619

### PR DESCRIPTION
**Pull request by giuseppe-steduto**
Closes #40

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # This file is part of REANA.
-# Copyright (C) 2022 CERN.
+# Copyright (C) 2022, 2023 CERN.
```
Comment (audrium) [inline Makefile:4]: Very minor: since this file was not changed yet, we could remove this addition

File: cmd/list.go [hunk 2]
```diff
@@ -285,7 +287,7 @@ func displayListPayload(
 		df = df.CBind(dataframe.New(colSeries))
 	}
 
-	df, err := formatter.SortDataFrame(df, sortColumn, true)
+	df, err := formatter.SortDataFrame(df, sortColumn, true, readableToRaw, humanReadable)
```
Comment (audrium) [inline cmd/list.go:290]: This approach works nicely! I guess the only problem is that `SortDataFrame()` was very generic before and now it's a bit coupled with `list` command. Since it's the only place where it's used it might be ok. Also, if we would use this function in some other command probably this logic would be beneficial to have. 
Just to document that another approach would be to create separate series for `sortable_run_number` and `sortable_size` before sorting and to drop it after

**Review by audrium — APPROVED** [review]
